Repository Ring-Us/ring-us.github.io, pull requests merged in 2025-05, with the labels that each got.

#59 RINGUS-75 feat: bookmark 페이지 구현
  package.json
  pnpm-lock.yaml
  src/app/routes/Router.tsx
  src/bookmark/api/.gitkeep
  src/bookmark/components/.gitkeep
  src/bookmark/components/BookmarkHeader.tsx
  src/bookmark/components/BookmarkMentorCard.tsx
  src/bookmark/components/BookmarkSortDropdown.tsx
  src/bookmark/hooks/.gitkeep
  src/bookmark/layouts/BookLayout.tsx
  src/bookmark/pages/Bookmark.tsx
  src/mentorship/components/mentorlist/MentorshipFilterBar.tsx
  src/mentorship/pages/mentorlist/MentorshipList.tsx
  tailwind.config.js
Labels: feat

#61 RINGUS-73 design: 멘토멘티 프로필 디자인 수정
  src/user/components/ProfileEdit/EditBio.tsx
  src/user/components/ProfileEdit/EditFields.tsx
  src/user/components/ProfileEdit/EditHashtags.tsx
  src/user/components/ProfileEdit/EditMessage.tsx
  src/user/components/ProfileEdit/EditPortfolio.tsx
  src/user/components/ProfileEdit/EditProfileSection.tsx
  src/user/components/ProfileEdit/EditProfileSectionMentee.tsx
  src/user/components/ProfileEdit/EditTime.tsx
  src/user/components/profileInfo/MenteeInfoBio.tsx
  src/user/components/profileInfo/MenteeInfoProfile.tsx
  src/user/components/profileInfo/MentorInfoBio.tsx
  src/user/components/profileInfo/MentorInfoFieldsHashtags.tsx
  src/user/components/profileInfo/MentorInfoMessage.tsx
  src/user/components/profileInfo/MentorInfoPortfolio.tsx
  src/user/components/profileInfo/MentorInfoProfile.tsx
  src/user/components/profileInfo/MentorInfoTime.tsx
  src/user/pages/ProfileEdit/MenteeInfo.tsx
  src/user/pages/ProfileEdit/MentorInfo.tsx
  src/user/pages/ProfileEdit/MentorProfileEdit.tsx
Labels: design

#66 RINGUS-86 feat: 제안하기 api 연결
  src/app/routes/Router.tsx
  src/mentorship/api/MentorViewApi.ts
  src/mentorship/api/SuggestApi.ts
  src/mentorship/components/suggestion/DateTimeSelectModal.tsx
  src/mentorship/components/suggestion/SuggestInfo.tsx
  src/mentorship/components/suggestion/SuggestSubject.tsx
  src/mentorship/components/suggestion/SuggestTime.tsx
  src/mentorship/pages/MentorInfoView.tsx
  src/mentorship/pages/Suggestion.tsx
  src/user/api/MenteeInfoApi.ts
  src/user/api/MentorInfoApi.ts
  src/user/components/ProfileEdit/EditProfileSection.tsx
  src/user/components/ProfileEdit/EditProfileSectionMentee.tsx
  src/user/menteetypes.ts
  src/user/pages/ProfileEdit/MenteeProfileEdit.tsx
  src/user/types.ts
Labels: feat

#67 RINGUS-75 refactor: 멘토 목록 필터링 부분 수정
  src/bookmark/pages/Bookmark.tsx
  src/global/components/JobCategories.tsx
  src/mentorship/components/mentorlist/MentorItem.tsx
  src/mentorship/components/mentorlist/MentorshipHeader.tsx
  src/mentorship/components/mentorlist/MentorshipListFilter.tsx
  src/mentorship/pages/Suggestion.tsx
  src/mentorship/pages/mentorlist/MentorshipList.tsx
  src/user/components/payment/DateSection.tsx
  src/user/components/payment/MentorSection.tsx
  src/user/components/profile/mentor/MentorProfile1.tsx
  src/user/pages/payment/Payment.tsx
Labels: refactor

#68 RINGUS-85 refactor: ENUM 데이터 변경 값 반영하기
  ringus.pem
  src/auth/components/signup/UsagePolicy.tsx
  src/content/terms-of-service.txt 
  src/global/components/JobCategories.tsx
  src/home/pages/HomePage.tsx
  src/mentorship/pages/MentorInfoView.tsx
  src/user/components/Mapping.ts
  src/user/components/profile/mentor/MentorFields.tsx
  src/user/components/profile/mentor/MentorProfile1.tsx
  src/user/components/profile/mentor/MentorTime.tsx
Labels: refactor

#71 RINGUS-88 feat: 포트폴리오 업로드 api 추가
  src/mentorship/api/MentorViewApi.ts
  src/user/api/MentorInfoApi.ts
  src/user/api/profileApi.ts
  src/user/components/ProfileEdit/EditHashtags.tsx
  src/user/components/ProfileEdit/EditPortfolio.tsx
  src/user/components/profileInfo/MenteeInfoBio.tsx
  src/user/components/profileInfo/MentorInfoPortfolio.tsx
  src/user/pages/ProfileEdit/MentorProfileEdit.tsx
  src/user/types.ts
Labels: feat

#72 RINGUS-79 feat: 마이페이지, 알림창, 상세보기 모달 퍼블리싱
  src/app/routes/Router.tsx
  src/auth/components/signup/UsagePolicy.tsx
  src/home/pages/HomePage.tsx
  src/home/pages/NotificationPage.tsx
  src/lib/privacyPolicy.ts
  src/lib/termsOfService.ts
  src/user/api/profileApi.ts
  src/user/components/FAQAccordion.tsx
  src/user/components/profile/mentee/MenteeProfile.tsx
  src/user/pages/Mypage.tsx
Labels: design, feat

#75 RINGUS-90 feat: 비밀번호 찾기(재설정) 기능 추가
  src/app/routes/Router.tsx
  src/auth/api/authApi.ts
  src/auth/api/emailApi.ts
  src/auth/components/password/ResetForm.tsx
  src/auth/components/password/VerifyForm.tsx
  src/auth/components/signup/EmailVerification.tsx
  src/auth/pages/PasswordRestPage.tsx
  src/auth/pages/SignInPage.tsx
  src/global/ui/Modal.tsx
  src/user/components/profile/mentee/MenteeCertification.tsx
  src/user/components/profile/mentee/MenteeProfile.tsx
  src/user/components/profile/mentor/MentorPortfolio.tsx
  src/user/components/profile/mentor/MentorProfile1.tsx
  src/user/pages/status/mentee/MenteeRequestStatus.tsx
  src/user/pages/status/mentor/MentorRequestStatus.tsx
Labels: feat

#79 RINGUS-93 feat: 이미지 경로 수정 및 북마크 api
  src/bookmark/components/BookmarkMentorCard.tsx
  src/bookmark/pages/Bookmark.tsx
  src/bookmark/store/BookmarkStore.ts
  src/mentorship/api/.gitkeep
  src/mentorship/api/fetchMentors.ts
  src/mentorship/components/.gitkeep
  src/mentorship/components/mentorlist/MentorItem.tsx
  src/mentorship/components/mentorlist/MentorshipListFilter.tsx
  src/mentorship/components/mentorlist/MentorshipSortDropdown.tsx
  src/mentorship/store/useMentorStore.ts
Labels: fix
