Repository Ring-Us/ring-us.github.io, pull requests merged in 2025-03, with the labels that each got.

#39 RINGUS-19 refactor: 추가된 디자인으로 멘토목록페이지 수정
  src/mentorship/components/mentorlist/MentorItem.tsx
  src/mentorship/components/mentorlist/MentorList.tsx
  src/mentorship/components/mentorlist/MentorshipFilterBar.tsx
  src/mentorship/components/mentorlist/MentorshipHeader.tsx
  src/mentorship/components/mentorlist/MentorshipListFilter.tsx
  src/mentorship/components/mentorlist/MentorshipSortDropdown.tsx
  src/mentorship/pages/mentorlist/MentorshipList.tsx
Labels: refactor

#42 RINGUS-47 feat: 멘토링 제안하기 페이지 개발
  package.json
  pnpm-lock.yaml
  src/app/routes/Router.tsx
  src/global/ui/Button.tsx
  src/global/ui/calendar.tsx
  src/mentorship/components/suggestion/DateTimeSelectModal.tsx
  src/mentorship/components/suggestion/SuggestInfo.tsx
  src/mentorship/components/suggestion/SuggestSubject.tsx
  src/mentorship/components/suggestion/SuggestTime.tsx
  src/mentorship/pages/MentorInfoView.tsx
  src/mentorship/pages/Suggestion.tsx
  src/user/components/ProfileEdit/EditBio.tsx
  src/user/components/profileInfo/MentorInfoProfile.tsx
  src/user/pages/ProfileEdit/MenteeInfo.tsx
  src/user/pages/ProfileEdit/MenteeProfileEdit.tsx
  src/user/pages/ProfileEdit/MentorInfo.tsx
  src/user/pages/ProfileEdit/MentorProfileEdit.tsx
  src/user/types.ts
Labels: feat

#44 RINGUS-51 feat: 멘토 프로필 & 인증서 등록
  public/icons/apple-touch-icon-180x180.png
  src/global/components/JobCategories.tsx
  src/home/pages/HomePage.tsx
  src/user/api/profileApi.ts
  src/user/components/ModalInput.tsx
  src/user/components/ModalMentorFields.tsx
  src/user/components/profile/mentee/MenteeProfile.tsx
  src/user/components/profile/mentor/ExperienceSelectModal.tsx
  src/user/components/profile/mentor/MentorCertification.tsx
  src/user/components/profile/mentor/MentorFields.tsx
  src/user/components/profile/mentor/MentorHashtags.tsx
  src/user/components/profile/mentor/MentorPortfolio.tsx
  src/user/components/profile/mentor/MentorProfile1.tsx
  src/user/components/profile/mentor/MentorProfile2.tsx
  src/user/components/profile/mentor/MentorProfile3.tsx
  src/user/components/profile/mentor/MentorTime.tsx
  src/user/components/profile/mentor/TimeModal.tsx
  src/user/pages/MenteeProfileRegistration.tsx
  src/user/pages/MentorProfileRegistration.tsx
  src/user/pages/Mypage.tsx
  src/user/types/defaultMenteeData.ts
  src/user/types/defaultMentorData.ts
  src/user/types/profileTypes.ts
Labels: feat

#48 RINGUS-50 feat: mentor목록 커서 기반 페이지네이션 및 api 연결
  ringus.pem
  src/mentorship/api/fetchMentors.ts
  src/mentorship/components/mentorlist/MentorItem.tsx
  src/mentorship/components/mentorlist/MentorList.tsx
  src/mentorship/components/mentorlist/MentorshipFilterBar.tsx
  src/mentorship/components/mentorlist/MentorshipFooter.tsx
  src/mentorship/components/mentorlist/MentorshipListFilter.tsx
  src/mentorship/components/mentorlist/MentorshipSortDropdown.tsx
  src/mentorship/pages/mentorlist/MentorshipList.tsx
  src/mentorship/pages/mentorlist/MentorshipList.types.ts
  src/user/components/payment/PaymentHeader.tsx
  src/user/pages/payment/Payment.tsx
Labels: feat

#51 RINGUS-68 fix: 프로필 등록 로직 변경
  src/user/components/profile/mentee/MenteeProfile.tsx
  src/user/components/profile/mentor/MentorProfile1.tsx
  src/user/components/profile/mentor/MentorProfile2.tsx
  src/user/components/profile/mentor/MentorTime.tsx
  src/user/pages/MenteeProfileRegistration.tsx
  src/user/pages/MentorProfileRegistration.tsx
Labels: fix

#53 RINGUS-69 fix: 멘토멘티 프로필 api 수정
  src/mentorship/api/MentorViewApi.ts
  src/mentorship/pages/MentorInfoView.tsx
  src/user/api/MentorInfoApi.ts
  src/user/components/ProfileEdit/EditImageModal.tsx
  src/user/components/ProfileEdit/EditProfileSection.tsx
  src/user/components/ProfileEdit/EditProfileSectionMentee.tsx
  src/user/components/profileInfo/MentorInfoProfile.tsx
  src/user/pages/ProfileEdit/MentorInfo.tsx
  src/user/types.ts
Labels: fix
